version: '3.1'
services:
    adminer:
        image:
            dockette/adminer:full
        restart:
            always
        ports:
            - "8088:80"

    dbPostgres:
        image: postgres:10
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: common

    redis:
        image: redis
        volumes:
          - ../data/redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always
